### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by Eeems** [Evidlo/remarkable_news#11]
Hey, could you add a license file so other developers can know what they can, and cannot do with your code?

**Comment by Evidlo** [comment]
Done

**Comment by matteodelabre** [comment]
I can’t find the license @Evidlo. Did you forget to add it?

**Comment by Evidlo** [comment]
@matteodelabre Looks like I forgot to push it initially.

**Comment by matteodelabre** [comment]
Thanks!
