### ISSUE TITLE
Download immediately when starting the program

### ISSUE THREAD

**Issue by anka-213** [Evidlo/remarkable_news#12]
Especially when testing, I would prefer to not have to wait the full timeout period when you change which thing it should be displaying before seeing the result. I know there is the `-test` option, but that disables the loop as well.

**Comment by Evidlo** [comment]
Why do you want the loop enabled during testing?

**Comment by anka-213** [comment]
The primary use case is when I update the systemd service file. I want to see the result as soon as I restart the service.

From what I can tell from reading the source code and from testing, it first waits the full timeout (e.g. an hour) and then it starts the first download.

**Comment by Evidlo** [comment]
This should be fixed with the latest commit.
