### ISSUE TITLE
Remarkable 2 compatibility

### ISSUE THREAD

**Issue by faroit** [Evidlo/remarkable_news#14]
I can't get it to work using macOS and remarkable2

```bash
Identity added: /Users/faro/.ssh/id_rsa (/Users/xxxx/.ssh/id_rsa)
Failed to stop renews.service: Unit renews.service not loaded.
make: *** [install_nyt] Error 5
```

any idea?

**Comment by Evidlo** [comment]
Try with the latest commit.  It should ignore this error if it occurs and continue on.

**Comment by faroit** [comment]
that helps put it doesn't seem to actually execute the service. Is there a way to manually trigger and debug it?

```bash
reMarkable: /etc/systemd/system/ systemctl -a | grep renews
  renews.service                                                                                                     loaded    active   running   New York Times
```

**Comment by Evidlo** [comment]
You can run `journalctl --unit renews -e` to check the logs.  The service will sit idle until you connect to a wifi network.

**Comment by faroit** [comment]
```bash
-- Logs begin at Wed 2020-11-04 21:23:59 UTC, end at Sat 2020-11-14 16:27:11 UTC. --
Nov 13 09:19:18 reMarkable systemd[1]: Started New York Times.
Nov 13 09:20:30 reMarkable systemd[1]: Stopping New York Times...
Nov 13 09:20:30 reMarkable systemd[1]: Stopped New York Times.
Nov 13 09:20:30 reMarkable systemd[1]: Started New York Times.
Nov 13 09:26:50 reMarkable systemd[1]: Stopping New York Times...
Nov 13 09:26:50 reMarkable systemd[1]: Stopped New York Times.
Nov 13 09:29:08 reMarkable systemd[1]: Started New York Times.
Nov 14 16:26:46 reMarkable systemd[1]: Stopping New York Times...
Nov 14 16:26:46 reMarkable systemd[1]: Stopped New York Times.
Nov 14 16:26:46 reMarkable systemd[1]: Started New York Times.
```

it showed all the timestamps where I manually restarted the service but it didn't write `suspended.png` at any time.

Is there a way to manually run the renews for testing?

**Comment by faroit** [comment]
@Evidlo 
> ```
> ./renews.arm -test -output /tmp/dump.png -verbose -url https://xkcd.com -xpath '//div[@id="comic"]/img/@src'
> ```

works fine for me, even when directly writing to `/usr/share/remarkable/suspended.png`. Still the service doesn't seem to be triggered by my remarkable 2. So I guess there is some problem detecting the if up/down?

**Comment by Evidlo** [comment]
> So I guess there is some problem detecting the if up/down?

The magic happens in wifi.go.  It waits for xochitl to emit a dbus message when WiFi is turned on.

**Comment by faroit** [comment]
> The magic happens in wifi.go. It waits for xochitl to emit a dbus message when WiFi is turned on.

i think the wifi interface has changed so this would need to be updated. What ID am I looking for?

**Comment by limyewjin** [comment]
Changing 'path=/org/freedesktop/network1/link/_34' to 'path=/org/freedesktop/network1/link/_311' worked for me for my remarkable 2

**Comment by Evidlo** [comment]
@limyewjin The contributor in [this PR](https://github.com/Evidlo/remarkable_news/pull/17) claimed that the ID is changing.  Is that not the case for you?

**Comment by faroit** [comment]
@Evidlo yes, I can confirm its changing on RM2

**Comment by limyewjin** [comment]
@Evidlo Ack. Too eager to see RM2 working on a wifi change and forgot to test another time. What about changing match rule to use arg0:
"interface='org.freedesktop.DBus.Properties',member='PropertiesChanged',arg0='org.freedesktop.network1.Link'"

**Comment by harrylepotter** [comment]
@limyewjin i'll give this a shot tonight. If there's any luck i'll drop it into my PR.

Thanks for those insights btw.

**Comment by Evidlo** [comment]
This should be fixed by https://github.com/Evidlo/remarkable_news/pull/17

**Comment by faroit** [comment]
@Evidlo #17 didn't fix it for me

**Comment by Evidlo** [comment]
@faroit Can you be more specific?  I don't have an rM2 so I rely on other people for debug information.

**Comment by Evidlo** [comment]
Well the dbus issue is fixed.  Seems like the remaining problem is https://github.com/Evidlo/remarkable_news/issues/25

**Comment by faroit** [comment]
> @faroit Can you be more specific? I don't have an rM2 so I rely on other people for debug information.

I can debug, if you provide some instruction how to look for the right network device.

**Comment by Evidlo** [comment]
@faroit The dbus problem is fixed from the log provided by @mjameson.

**Comment by faroit** [comment]
Yes. Works for me now. Thanks for your effort
