### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ngamarra** [Evidlo/remarkable_news#20]
Is it possible for a kind soul to help walk me through a basic install on macos big sur for a unix noob?

I downloaded and installed go. I was able to download remarkable_news with the git command. However as soon as I tried the "make download_prebuilt" command it is unable to locate the link. If I try to use make to install_nyt I get the following output:

`make install_nyt
go get ./...
go get _/remarkable_news: copying /var/folders/j0/h8n8yvn93yl_0dpb902y79hr0000gn/T/go-build588194722/b001/exe/a.out: open /bin/remarkable_news: operation not permitted
make: *** [renews.arm] Error 1
`

Any help would be greatly appreciated, as this seems really cool!

**Comment by Evidlo** [comment]
What is the error you get with `make download_prebuilt`?

**Comment by ngamarra** [comment]
This is the output:
`wget http://github.com/evidlo/remarkable_news/releases/latest/download/release.zip
make: wget: No such file or directory`

**Comment by jedahan** [comment]
Can you try ‘brew install wget’ and try again?

**Comment by Evidlo** [comment]
OK, maybe I'll switch to curl since OSX doesn't ship with wget.

**Comment by ngamarra** [comment]
Thanks for your help so far!

I installed wget and was able to download and unzip renews.x86. However, now when i attempt to `make install_nyt` I get the following error:

`eval ""
eval SSH_AUTH_SOCK=/var/folders/j0/h8n8yvn93yl_0dpb902y79hr0000gn/T//ssh-YX4476RbW88r/agent.58401; export SSH_AUTH_SOCK; SSH_AGENT_PID=58402; export SSH_AGENT_PID; echo Agent pid 58402;
Agent pid 58402
ssh-add
make: *** [install_nyt] Error 1`

**Comment by Evidlo** [comment]
Can you just post a screenshot of what you're seeing in the terminal, because I can't make sense of what you're pasting.

**Comment by Evidlo** [comment]
Reopen if this is still an issue.
