### ISSUE TITLE
Unable to fetch NYT

### ISSUE THREAD

**Issue by atharvajohri** [Evidlo/remarkable_news#24]
I checked the logs, it's trying to fetch the image from "https://cdn.newseum.org/dfp/jpg08/lg/NY_NYT.jpg"
But fails. Full log:
`
[Failed to fetch url]
"panic: Get "https://cdn.newseum.org/dfp/jpg08/lg/NY_NYT.jpg": write tcp [2a02:8109:9a80:1f94:d612:43ff:fef3:58fc]:51006->[2606:4700:3032::6818:7d40]:443: write: broken pipe
`

**Comment by Evidlo** [comment]
This is related to https://github.com/Evidlo/remarkable_news/issues/23
