### ISSUE TITLE
v2.5.0.27 has changed the suspend screen

### ISSUE THREAD

**Issue by fringley** [Evidlo/remarkable_news#27]
This looks like it is now splash.png.... however, overwriting this file doesn't seem to make any difference.  There is also now a splash.dat file that I suspect is used to create the splash screen rather than using the png now?

**Comment by Evidlo** [comment]
Move this discussion to  https://github.com/Evidlo/remarkable_news/issues/25

**Comment by fringley** [comment]
Please ignore this original comment.  Splash displays "Remarking is STARTING" not "SLEEPING".  I mis-read!

The behaviour now is as #25

**Comment by lgnap** [comment]
a `systemctl restart xochitl.service` is working to refresh the suspend screen.
But it's like a restart of the interface, interrupting what you're doing :-(
