### ISSUE TITLE
mac installation error

### ISSUE THREAD

**Issue by GliderGeek** [Evidlo/remarkable_news#3]
- Mac OS 10.15.3
- go1.13.5 / go1.14.2 darwin/amd64 (installed with homebrew)
- GNU Make 3.81
- ZSH

tried the install as described in the README and got the following error:

```console
$ make install_nyt
go get ./...
go get: no install location for directory ~/remarkable_news outside GOPATH
	For more details see: 'go help gopath'
make: *** [renews.arm] Error 1
```

will try to fix this and report if i encounter other problems

**Comment by GliderGeek** [comment]
upgrading to go 1.14.2 does not make a change

**Comment by GliderGeek** [comment]
https://stackoverflow.com/a/27428046/4629173
this solved it for (export GOPATH and GOBIN)

**Comment by GliderGeek** [comment]
This bring me a bit further: `renews.arm` is produced. However another error pops up:
```console
$ make install_nyt
go get ./...
env GOOS=linux GOARCH=arm GOARM=5 go build -o renews.arm
ssh-add
make: *** [install_nyt] Error 1
```

**Comment by GliderGeek** [comment]
after adding an ssh key (per https://www.reddit.com/r/RemarkableTablet/comments/78u90n/passwordless_ssh_setup_for_remarkable_tablet/?utm_source=share&utm_medium=web2x)
i got a step further.

unfortunately another error:
```console
$ make install_nyt
go get ./...
env GOOS=linux GOARCH=arm GOARM=5 go build -o renews.arm
ssh-add
Identity added: ***
ssh root@10.11.99.1 systemctl stop renews
Failed to stop renews.service: Unit renews.service not loaded.
make: *** [install_nyt] Error 5
```

**Comment by GliderGeek** [comment]
service is not yet present. thus the first time, that command should not be executed.
out-commenting this line in [makefile](https://github.com/Evidlo/remarkable_news/blob/2aece79031b466e77bbd9e343e66a57c1dc0ae9d/Makefile#L30)

(only needed for first run)

**Comment by GliderGeek** [comment]
[The block of with ssh context](https://github.com/Evidlo/remarkable_news/blob/2aece79031b466e77bbd9e343e66a57c1dc0ae9d/Makefile#L38) did not work for me. replaced it with:

```console
ssh root@$(host) systemctl daemon-reload
ssh root@$(host) systemctl enable renews
ssh root@$(host) systemctl restart renews
```

**Comment by GliderGeek** [comment]
It now seems to work 🎉 😄 
thanks for the nice project, let me know if you need some help debugging some of the problems i described above

**Comment by Evidlo** [comment]
> The block with ssh context did not work for me. replaced it with:

That's weird.  OSX uses either bash or zsh and both of those should support that syntax.

**Comment by GliderGeek** [comment]
will do so

**Comment by Evidlo** [comment]
So what's the verdict here?  Does the SSH heredoc work on OSX?

**Comment by acrogenesis** [comment]
@Evidlo I'm on macOS Big Sur and I needed both of @GliderGeek modifications for the install to work.
