### ISSUE TITLE
The Newseum has closed it doors and thus news sources are no longer updating

### ISSUE THREAD

**Issue by gabefair** [Evidlo/remarkable_news#31]
The Newseum in Washington, D.C. closed its doors on Pennsylvania Avenue on December 31, 2019, after 11 years and nearly 10 million visitors. The Freedom Forum said that operating the attraction was financially unstable.

New York Times jpg downloads are no longer working

**Comment by Evidlo** [comment]
Both the `nyt` and `nyt-hq` services are working fine for me.

**Comment by Evidlo** [comment]
`nyt.service` now pulls from frontpages.com
