### ISSUE TITLE
High CPU usage with waiting for wifi to connect. Recommended systemd Timer module

### ISSUE THREAD

**Issue by alexteal** [Evidlo/remarkable_news#32]
Hey there, just glanced at the guidelines but I'm not really sure if this proper formatting or anything. Also, side note: this is the first github issue I've opened on anyone else's project, ever. 

# Battery drain with waiting for wifi

Tested on Remarkable 2 

Here's a quick snapshot from top when renews.arm is idle: 
```bash
 5242     1 root     S     782m  80%   0% /home/root/renews.arm -output /usr/share/remarkable/suspended.png -verbose -co...
```

As you can see, whatever library or module is waiting for wifi seems to be using a lot of resources, which is entirely unnecessary for updating the screensaver once daily. 

### hacky fix
I hacked together a fix on my end, but it's not very clean and I didn't spend much time learning Go, so I won't be sending a PR right now. Currently the fix I'm using is a systemd timer module that triggers at 4:00am daily. It works great so far, since even if the remarkable is asleep when the timer should trigger, it will trigger as soon as the remarkable wakes. And, in the main.go I stuck this at the end: 

### main.go
```go
//line 25
//define exit flag
//###########################################
    scale := flag.Float64("scale", 1, "scale image prior to centering")
    exit := flag.Bool("exit", false, "exit after save")
    // top := flag.Int("top", 0, "crop from top")
```

```go
//line 69
// exit if flag is set
//###########################################
    img = adjust(img, *mode, *scale)
    imaging.Save(img, *output)
    debug("Image saved to ", *output)
    if *exit {
        os.Exit(0)
    }
```
### /etc/systemd/system/renews.timer
```systemd
[Unit]
Description=trigger renews.service
After=network-online.target
Wants=network-online.target

[Timer]
Unit=renews.service
OnCalendar=*-*-* 4:00:00

[Install]
WantedBy=multi-user.target
```
### nyt module
```systemd

[Unit]
Description=nyt_hq
After=network-online.target
Wants=network-online.target

# sidebar: looks like the nyt_hq endpoint is down.

[Service]
ExecStart=/home/root/renews.arm \
-output /usr/share/remarkable/suspended.png \
-verbose \
-url https://nyt-today.acrogenesis.com/nyt \
-mode center

[Install]
WantedBy=multi-user.target
```

So, yeah it's a dirty fix, but it prevents the module from continuing to drain battery unnecessarily. 

Let me know what you all think about this. 

I can work on making it a little prettier and send in a PR if you'd like, but I'm aware this undermines a large chunk of work that was getting this to run based on wifi status, so I understand if this isn't the best move.

**Comment by Evidlo** [comment]
@alexteal Sorry for the slow response.  Isn't that 80% in the `VSZ` column of `top`, meaning memory and not CPU usage?

**Comment by alexteal** [comment]
Oh. It is. 

Huh. How about that. My bad. 

It's been a while since I've looked at this, and I've been using that "temporary fix" for over a year now, and no complaints so far. Take that as you will, I suppose you can close this ticket now lol.

**Comment by Evidlo** [comment]
Sure, hope the app has been working well for you!
