### ISSUE TITLE
suspended.png cached on 3.0.4.1305

### ISSUE THREAD

**Issue by hevalito** [Evidlo/remarkable_news#34]
On the ReMarkable Version 3.0.4.1305 the suspended.png image seems to be cached. It only refreshes upon reboot. I think most of you know about this issue - is there any known workaround?

**Comment by Evidlo** [comment]
This is a known issue: https://github.com/Evidlo/remarkable_news/issues/25

This is fixed in the `rmhacks` patch mentioned in the issue above.
