### ISSUE TITLE
New York Times (HQ) with wrong info (xkcd)

### ISSUE THREAD

**Issue by FapfapGit** [Evidlo/remarkable_news#35]
The link to **New York Times (high quality)** is wrong and points to `sh /dev/stdin xkcd` 

<img width="859" alt="image" src="https://github.com/Evidlo/remarkable_news/assets/141946554/9630b588-06d9-405a-8b2d-27b1121c4482">

—
Looks like it should point to `nyt-hq` from this comment: https://github.com/Evidlo/remarkable_news/issues/31#issuecomment-913175665

**Comment by FapfapGit** [comment]
Looks like it should point to `nyt-hq`

https://github.com/Evidlo/remarkable_news/issues/31#issuecomment-913175665

**Comment by Evidlo** [comment]
Thanks, fixed.
