### ISSUE TITLE
high resolution new york times

### ISSUE THREAD

**Issue by billiob** [Evidlo/remarkable_news#6]
Just letting you know that you can download a high resolution of the homepage of new york times at such an url: https://static01.nyt.com/images/2020/04/23/nytfrontpage/scan.pdf

Found out thanks to this article that is kinda related: https://onezero.medium.com/the-morning-paper-revisited-35b407822494

**Comment by Evidlo** [comment]
Thanks for the info.  Converting pdf to png is difficult and can't really be done in pure Go.

**Comment by acrogenesis** [comment]
@Evidlo @billiob I've made a small service that pulls the latest NYT pdf converts it to jpg and does the necessary conversion. Here's the source code https://github.com/acrogenesis/nyt-today

You just have to change `nyt.service`
```
    -url https://nyt-today.acrogenesis.com/nyt \
    -mode center
```

**Comment by Evidlo** [comment]
> [@Evidlo][] [@billiob][] I've made a small service that pulls the latest NYT pdf converts it to jpg and does the
> necessary conversion. Here's the source code https://github.com/acrogenesis/nyt-today
> 
> You just have to change nyt.service
> 
>         -url https://nyt-today.acrogenesis.com/nyt \
>         -mode center

We can have two NYT sources.  Submit a PR and I'll merge it.
