### ISSUE TITLE
why GOARM=5 instead of GOARM=7?

### ISSUE THREAD

**Issue by GliderGeek** [Evidlo/remarkable_news#7]
i was wondering why you are using GOARM=5 instead of GOARM=7 in you compilation?

[the remarkable site](https://support.remarkable.com/hc/en-us/articles/360002634397-About-reMarkable-1) lists a `ARM A9 CPU`.

according to [wikipedia](https://en.wikipedia.org/wiki/ARM_Cortex-A9) the A9  implements the `ARMv7` architecture.

according to [this wiki](https://github.com/golang/go/wiki/GoArm) the GOARM=7 flag should be used.

**Comment by Evidlo** [comment]
No specific reason.  It should probably be changed.
